from email.message import EmailMessage
import smtplib
# Email and Password
EMAIL_ID = "mail@gmail.com"
PASSWORD = "password"
msg= EmailMessage()

msg['Subject' ] = 'Email with attachments using python' #Subject
msg['From '] = EMAIL # Sender's mail
msg['To'] = [ 'friend@gmail.com'] //reciever
message = " Mail is generated by python"
msg.set_content(message)

attachments = [ ' ' ] # address of  the files to be attached

for path in attachments:
    with open(path,'rb')as file:
        data = file.read()
        name = path.split("\\" )[-1]

    msg.add_attachment(data,maintype = 'application' , subtype = 'octet-stream'
                         filename = name )

with smtplib.SMTP_SSL('smtp.gmail.com' , 465 )as smtp:
    smtp.login(EMAIL , PASSWORD)
    smtp.send_message(msg)
